import { readFile, readdir, stat, writeFile } from "node:fs/promises";
import { extname, join } from "node:path";

const textExtensions = new Set([".css", ".html", ".js", ".webmanifest", ".xml"]);

/** Escapes text before placing it in a regular expression. */
const escapeRegExp = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/**
 * Returns a function that adapts compiled root URLs to GitHub Project Pages.
 * Production source and the regular Azure build remain unchanged.
 */
export function previewRewriter({ base, origin }) {
  if (!/^\/[A-Za-z0-9._-]+$/.test(base)) throw new Error("Invalid GitHub Pages base path");
  const parsedOrigin = new URL(origin);
  if (parsedOrigin.protocol !== "https:") throw new Error("GitHub Pages origin must use HTTPS");

  const baseName = escapeRegExp(base.slice(1));
  const localRoot = new RegExp(`([=\"'\u0060(\\s,])\\/(?!\\/|${baseName}(?:\\/|[\"'\u0060?#\\s)\\]]))(?=[A-Za-z0-9_])`, "g");
  const homeAttribute = /(\b(?:href|action)=)(["'])\/\2/g;
  const absoluteRoot = new RegExp(`${escapeRegExp(parsedOrigin.origin)}\\/(?!${baseName}(?:\\/|$))`, "g");

  return (source) => source
    .replace(homeAttribute, `$1$2${base}/$2`)
    .replace(localRoot, `$1${base}/`)
    .replace(absoluteRoot, `${parsedOrigin.origin}${base}/`);
}

/** Recursively returns text assets generated by Astro. */
async function findTextFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(entries.map(async (entry) => {
    const path = join(directory, entry.name);
    if (entry.isSymbolicLink()) throw new Error(`Pages artifact contains a symlink: ${path}`);
    if (entry.isDirectory()) return findTextFiles(path);
    return textExtensions.has(extname(entry.name)) ? [path] : [];
  }));
  return nested.flat();
}

/** Calculates the final artifact size before it is uploaded to Pages. */
async function directorySize(directory) {
  let total = 0;
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    total += entry.isDirectory() ? await directorySize(path) : (await stat(path)).size;
  }
  return total;
}

/** Prepares a private-to-search, static-only GitHub Pages review artifact. */
export async function preparePages(directory, options) {
  const rewrite = previewRewriter(options);

  for (const file of await findTextFiles(directory)) {
    let source = rewrite(await readFile(file, "utf8"));
    if (extname(file) === ".html") {
      source = source.replace(
        "</head>",
        '<meta name="robots" content="noindex,nofollow,noarchive"><meta name="crystal-preview" content="pages"></head>',
      );
    }
    if (extname(file) === ".webmanifest") {
      source = source.replace(/("start_url"\s*:\s*")\/("?)/, `$1${options.base}/$2`);
    }
    await writeFile(file, source);
  }

  await writeFile(join(directory, ".nojekyll"), "");
  await writeFile(join(directory, "robots.txt"), "User-agent: *\nDisallow: /\n");

  const bytes = await directorySize(directory);
  if (bytes > 950_000_000) throw new Error("GitHub Pages artifact exceeds the 950 MB safety budget");
  console.log(`GitHub Pages preview prepared: ${bytes} bytes`);
}
