import { locales, pageOrder, type LocaleId, type PageKey } from "@/data/site";

/** One fully resolved, build-time route. */
export interface RouteEntry {
  /** Locale identifier used to select content. */
  localeId: LocaleId;
  /** Stable page family. */
  pageKey: PageKey;
  /** Public pathname with a trailing slash. */
  pathname: string;
  /** Catch-all route parameter without surrounding slashes. */
  slug: string;
}

/** Every canonical route generated by Astro. */
export const routes: RouteEntry[] = (Object.keys(locales) as LocaleId[]).flatMap((localeId) => {
  const locale = locales[localeId];
  return pageOrder.map((pageKey) => {
    const pathname = locale.paths[pageKey];
    return { localeId, pageKey, pathname, slug: pathname.replace(/^\/+|\/+$/g, "") };
  });
});

/** Resolves a generated route or fails the build instead of emitting incomplete content. */
export function getRoute(localeId: LocaleId, pageKey: PageKey): RouteEntry {
  const route = routes.find((entry) => entry.localeId === localeId && entry.pageKey === pageKey);
  if (!route) throw new Error(`Missing route for ${localeId}/${pageKey}`);
  return route;
}
